# =======================================
# agent based model markup language (absml)
# =======================================
[global]
target_fps = 120
width = 1020
height = 810

[spawnerMain]
# line = [[2, 20], [2, 15]]
line = [[16, 24], [21, 24]]
wait = 0
limit = 100
children = ["areaMain"]

[areaMain]
area = [16, 3, 5, 1]
dimensions = [1, 1]