[global]
width = 1050
height = 810
target_fps = 120
draw = false

[areaQueue]
area = [270, 90, 500, 30]
dimensions = [7, 1]
wait_mode = "queue"
kill = false
children = ['areaHelp']
chances = [1]
queue_positions = [[7, 8]]
queue_initiator = 0

[areaHelp]
area = [270, 90, 500, 30]
dimensions = [7, 1]
wait_mode = "att"
wait = 3000
kill = false
children = ['areaLounge']
chances = [1]

[areaLounge]
area = [660, 390, 270, 240]
dimensions = [5, 5]
wait_mode = "att"
kill = false
children = []
chances = [1]

[spawner0]
line = [[60.0, 240.0], [60.0, 360.0]]
wait = 300
limit = 100000
children = ['areaQueue']
chances = [1]

[polygon0]
points = [[60.0, 240.0], [60.0, 90.0], [270.0, 90.0]]
connect = false
invisible = false

[polygon1]
points = [[780.0, 90.0], [960.0, 90.0], [960.0, 300.0]]
connect = false
invisible = false

# VECTOR FIELDS

[vector0]
pos = [7, 8]
angle = 0.767944870877505

