[global]
width = 810
height = 810
target_fps = 120
draw = false

[revolverEntrance]
p1 = [390, 630]
n = 4
l = 55
av = 0.03

[polygon0]
points = [[330.0, 690.0], [330.0, 600.0], [180.0, 600.0]]
connect = false
invisible = false

[polygon1]
points = [[450.0, 690.0], [450.0, 600.0], [690.0, 600.0]]
connect = false
invisible = false

[polygon2]
points = [[330.0, 120.0], [330.0, 210.0], [180.0, 210.0]]
connect = false
invisible = false

[polygon3]
points = [[450.0, 120.0], [450.0, 210.0]]
connect = false
invisible = false

[polygon4]
points = [[690.0, 210.0], [450.0, 210.0]]
connect = false
invisible = false

[spawnerTop]
line = [[330.0, 90.0], [450.0, 90.0]]
wait = 200
limit = 100
children = ['areaBottom']
chances = [1]

[areaBottom]
area = [330, 720, 120, 90]
dimensions = [1, 1]
wait_mode = "pv"
kill = true
children = []
chances = [1]

[areaTop]
area = [330, 0, 120, 210]
dimensions = [1, 1]
wait_mode = "pv"
kill = true
children = []
chances = [1]

# VECTOR FIELDS

